### ISSUE TITLE
UI |  Favicon.ico

### ISSUE THREAD

**Issue by PiotrWR** [nowakprojects/CodersCamp2020.Project.JavaScript.StarWarsQuiz#45]
### Kryteria akceptacji
**Należy zweryfikować i skonsultować, a także ewentualnie uaktualnić przed rozpoczęciem prac nad zgłoszeniem.**

- [x] Dodać favicon

**Comment by nowakprojects** [comment]
A mamy jakiś projekt grafiki :) ?

**Comment by PiotrWR** [comment]
> A mamy jakiś projekt grafiki :) ?

Myślałem, o wrzuceniu logo "starwars".
Następnym razem napiszę w moim zadanku!

**Comment by nowakprojects** [comment]
> > A mamy jakiś projekt grafiki :) ?
> 
> Myślałem, o wrzuceniu logo "starwars".
> Następnym razem napiszę w moim zadanku!

Możesz to zedytować :) To jestem za.

Approved.

**Comment by tomdworniczak** [comment]
Approved :)

**Comment by lamparina** [comment]
Approved
